### PR TITLE
CLOUD-214 test

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Comment by hors** [comment]
PXC docker - perconalab/percona-xtradb-cluster-operator:PR-1

**Comment by hors** [comment]
PXC docker - perconalab/percona-xtradb-cluster-operator:pr-1

**Comment by hors** [comment]
PXC docker - perconalab/percona-xtradb-cluster-operator:pr-1

**Comment by hors** [comment]
PXC docker - perconalab/percona-xtradb-cluster-operator:

**Comment by hors** [comment]
PXC docker - perconalab/percona-xtradb-cluster-operator:PR-1-654165e

**Comment by hors** [comment]
PXC docker - perconalab/percona-xtradb-cluster-operator:PR-1-2d77346

**Comment by hors** [comment]
PXC docker - perconalab/percona-xtradb-cluster-operator:PR-1-52a1931

**Comment by JNKPercona** [comment]
PXC docker - perconalab/percona-xtradb-cluster-operator:PR-1-52a1931

**Pull request closed without merging**
