### PR TITLE
CLOUD-214 test PR

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Comment by hors** [comment]
PXC docker - perconalab/percona-xtradb-cluster-operator:pr-2

**Comment by hors** [comment]
PXC docker - perconalab/percona-xtradb-cluster-operator:pr-2

**Comment by hors** [comment]
PXC docker - perconalab/percona-xtradb-cluster-operator:

**Comment by JNKPercona** [comment]
PXC docker - perconalab/percona-xtradb-cluster-operator:pr-2

**Pull request closed without merging**
